### PR TITLE
Use correct goroot source path for Go 1.4.

### LINKED ISSUE #3: "std" pattern does not work as expected with latest version.
On Go 1.4.1, using "std" as input results in no packages matched. Using latest gotool commit 37b67b9f055653df36c7ef6016c4feed95ad87bf.

Using "all" works as expected and matches all packages.

Using a pattern like "...tools" correctly expands it to matching packages.

```
$ goe 'gotool.ImportPaths([]string{"...importer"})'
([]string)([]string{
	(string)("golang.org/x/tools/go/gccgoimporter"),
	(string)("golang.org/x/tools/go/gcimporter"),
	(string)("golang.org/x/tools/go/importer"),
	(string)("honnef.co/go/importer"),
})
$ goe 'gotool.ImportPaths([]string{"std"})'
warning: "std" matched no packages
([]string)([]string{})
$ goe 'gotool.ImportPaths([]string{"all"})'
([]string)([]string{
	(string)("archive/tar"),
	(string)("archive/zip"),
	(string)("bufio"),
	(string)("bytes"),
	(string)("cmd/addr2line"),
	(string)("cmd/cgo"),
...
```

### PR DESCRIPTION
**Pull request by shurcooL**
- In Go 1.4, the goroot source path has moved from `$GOROOT/src/pkg` to
`$GOROOT/src`. This updates the variable and allows "std" pattern to work
correctly again.
- Fixes #3.
- Fixes dominikh/implements#11.

### CODE REVIEW

File: go13.go [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// +build !go1.4
```
Comment (shurcooL) [inline go13.go]: For reference, I used the [`exact`](https://github.com/golang/tools/tree/1afe783e9f23b46389ab7a439ed4e0eee558382a/go/exact) package as reference for the naming/style of a Go 1.4+ and earlier solution.

File: match.go [hunk 2]
```diff
@@ -41,10 +41,7 @@ import (
 	"strings"
 )
 
-var (
-	goroot       = filepath.Clean(runtime.GOROOT())
-	gorootSrcPkg = filepath.Join(goroot, "src/pkg")
-)
+var goroot = filepath.Clean(runtime.GOROOT())
```
Comment (dominikh) [inline match.go]: The `goroot` variable is only used in `go1.3.go` and `go1.4.go`, it should probably be moved to these files respectively.

Comment (shurcooL) [inline match.go]: Thanks. I thought `goroot` was used elsewhere, that's why I left it alone, since its value does not differ between the two versions.

However, since it's only used for `gorootSrcPkg`, it makes sense to move it there. In fact, it can be just removed.

Done in fb417b44ad915a5391a308f01e6a41117acced3d.

**Comment by kisielk** [comment]
Cool. Thanks :)
